export interface Issue {
  userDocIdentification: string,
  providerEconomicRegistration?: string | null,
  providerCnpjOrCpf: string,
  series: number,
  type: string,
  borrowerType: number,
  borrower: string,
  borrowerCnpjOrCpf: string,
  borrowerEconomicRegistration?: string | null,
  borrowerCity: string,
  borrowerCep: string,
  borrowerCountry: string,
  borrowerStreet: string,
  borrowerDistrict: string,
  placeOfProvision: string,
  serviceList: string,
  placeOfIncidence: string,
  taxSituation: string,
  timboRate: number,
  serviceValue: number,
  discountUnconditional: number,
  dedutionAmount: number,
  calculationBase: number,
  ISSQN: number,
  ISSRF: number,
  description: string,
  incomeTax: number,
  pis: number,
  cofins: number,
  amount: number,
  unconditionalDiscount?: number | null,
  deduction: number,
  totalIssqn: number,
  totalIssrf: number,
  totalFederalTaxes: number,
  conditionalDescount: number,
  netValue: number
}
