export interface Message {
  [key: string]: string
}

const messages: Message = {
  //Sucesso
  '1': 'Nota emitida.',

  //Validação de Usuário
  '131': 'Não foi possível validar o usuário logado!',
  '132': 'Usuário ou Senha inválidos!',
  '133': 'Usuário informado encontra-se desativado.',
  '134': 'Usuário informado não cadastrado como contribuiente.',
  '135': 'Usuário informado não cadastrado como econômico.',
  '136': 'Código da cidade do contribuinte informado não encontrado no cadastro.',
  '144': 'Login informado deve conter apenas números.',
  '145': 'Não foi possível estabelecer uma conexão com o link informado.',

  //Validação do privilégio do usuário
  '137': 'Usuário informado sem privilégio para acessar o módulo de emissão de NFS-e.',

  //Validação de autorização de emissão de NFS-e
  '138': 'Usuário informado sem permissão para acessar o módulo de emissão de NFS-e.',
  '139': 'Cadastro informado sem autorização para emissão de NFS-e.',

  //Validação de prestador de serviço
  '2': 'CPF/CNPJ do prestador não informado.',
  '3': 'CPF/CNPJ do prestador não é válido.',
  '4': 'Prestador não cadastrado como econômico.',
  '5': 'Usuário logado é diferente do prestador informado e não existe relacionamento contador/cliente entre ambos.',
  '6': 'Prestador informado encontra-se baixado.',
  '111': 'Prestador informado não cadastrado no único.',
  '245': 'Contador não autorizado a emitir NFS-e pelo Econômico.',

  //Validação de cidade do prestador
  '7': 'Cidade do prestador não informada.',
  '8': 'Cidade do prestador informado não é um código válido.',
  '9': 'Cidade do prestador informado não encontra-se cadastrada na base de dados do datacenter.',

  //Validação de solicitação de impressão de NFS-e
  '10': 'Solicitação de emissão para NFS-e não encontrada.',

  //Validação de tomador de serviço
  '11': 'Tipo do tomador ("F" - Física ou "J" - Júridica ou "E" - Estrangeiro) está ausente.',
  '12': 'Tipo do tomador foi preenchido incorretamente, utilize apenas "F" ou "J" ou "E".',
  '13': 'CPNJ do tomador está ausente e o tipo está setado como "J" (Pessoa Jurídica).',
  '14': 'CNPJ do tomador informado está preenchido incorretamente.',
  '176': 'As configurações do respectivo cliente exigem que o campo CPF/CNPJ do tomador seja informado.',
  '190': 'Para usar TRF ou TIST é necessário que seja informado um tomador de serviço.',
  '191': 'Tomador e prestador do serviço deve possuir 8 dígitos.',
  '195': 'O CEP da cidade do tomador do serviço deve possuir 8 dígitos.',
  '228': 'O município não contém configurações para utilizar o cadastrado alternativo de endereços para o tomador de serviço da NFS-e.',
  '229': 'O tomador do serviço possui cadastro econômico no município. Não é possível inserir um novo endereço.',
  '230': 'O DDD comercial do tomador de serviço contém mais que 3 caracteres.',
  '231': 'O DDD residencial do tomador de serviço contém mais que 3 caracteres.',
  '233': 'O DDD do FAX do tomador de serviço contém mais que 3 caracteres.',
  '234': 'O fone comercial do tomador de serviço contém mais que 9 caracteres.',
  '235': 'O fone residencial do tomador de serviço contém mais que 9 caracteres.',
  '236': 'O novo endereço do tomador é igual ao endereço já cadastrado no único. Altere a tag "endereco_informado".',
  '237': 'A opção de "Cadastro de novos endereços para tomadores de serviço", não está disponível para tomadores do tipo estrangeiro.',
  '238': 'O logradouro informado para o endereço do tomador do serviço, não consta cadastrado na base de dados.',
  '239': 'O bairro informado para o endereço do tomador do serviço, não consta cadastrado na base de dados.',
  '240': 'Erro na tentativa de inserir na tabela "dcarq.wm_endereco_tomador".',
  '241': 'Número da residência do tomador do serviço não pode conter mais que 8 caracteres.',

  //Inserindo novo tomador do serviço
  '15': 'Tipo (Jurídico ou Físico) do tomador não definido.',
  '16': 'CPF/CNPJ do tomador não definido.',
  '17': 'CPF/CNPJ do tomador não é um CPF/CNPJ válido.',
  '18': 'CPF do tomador não é um CPF válido.',
  '19': 'CNPJ do tomador não é um CNPJ válido.',
  '20': 'Nome/Razão Social do tomador não definido.',
  '21': 'Endereço (logradouro) do tomador não definido.',
  '22': 'Código da cidade do tomador não definido.',
  '23': 'Código da cidade do tomador não é um código válido.',
  '24': 'Cidade do tomador não cadastrada na base de dados do datacenter.',
  '25': 'Erro na tentativo de gravar na monitora (Novo cadastro tomador).',
  '164': 'O tipo do tomador foi declarado com "E" (Estrangeiro) porém o IDENTIFICADOR não foi informado.',
  '165': 'Para utilizar um tomador estrangeiro é necessário informar os campos identificador, nome_razao_social, logradouro, cidade, estado, país.',
  '171': 'O nome do tomador deve ser informado de maneira composta (Nome + Sobrenome)',
  '174': 'Não é possível inserir um tomador de serviço estrangeiro utilizando como país o Brasil.',
  '196': 'Bairro do tomador não definido.',
  '197': 'Nome/Razão Social do tomador invalido.',
  '198': 'Endereço (lorgadouro) do tomador invalido.',
  '199': 'Bairro do tomador invalido.',
  '200': 'E-mail(s) informado para o tomador é inválido.',
  '242': 'Erro na tentativa de inserir um registro na tabela nfw_tomadores_favoritos.',

  //Valores da NFS-e
  '26': 'O valor total da NFS-e não foi declarado corretamente.',
  '27': 'O valor total da NFs-e não pode ser zero (0,00).',
  '28': 'O valor do desconto não pode ser superior ao valor total da NFS-e.',
  '29': 'A soma do valor do IR + INSS + Contribuição Social não pode ser superior ao valor total da NFS-e.',

  //Itens da NFS-e
  '30': 'Nenhum código da lista de serviço foi informado.',
  '31': 'Código do item da lista de serviço está preenchido incorretamente.',
  '32': 'Código do local da prestação de serviço está preenchido incorretamente.',
  '33': 'Descritivo do serviço prestado não foi preenchido.',
  '34': 'Alíquota do serviço prestado não foi preenchida corretamente.',
  '35': 'Situação tributária do serviço prestado não foi preenchido corretamente.',
  '36': 'Valor tributável do serviço prestado não foi preenchido corretamente.',
  '37': 'Valor tributável do serviço prestado não pode ser zerado.',
  '38': 'Valor da dedução do serviço prestado não está preenchido corretamente.',
  '39': 'Valor do ISSRF para o serviço prestado não está preenchido corretamente.',
  '40': 'Os códigos da lista de serviço não podem ser repetidos.',
  '41': 'Econômico (Prestador do serviço) não encontrado.',
  '42': 'Não existe relacionamento entre as atividades e a lista de serviço do prestador.',
  '43': 'Codigo da lista de serviço ausente.',
  '44': 'Código da lista de serviço não é um número válido.',
  '45': 'Código da lista de serviço sem relacionamento com a tabela iss.atiser para o prestador do serviço informado.',
  '46': 'Código da lista de serviço não encontrado.',
  '47': 'Nenhuma cidade (local da prestação do serviço) foi informada.',
  '48': 'Código do local da prestação do serviço ausente.',
  '49': 'Código do local da prestação do serviço não é um código válido.',
  '50': 'Nenhuma "descrição" do serviço realizado foi informado.',
  '51': 'Descrição do serviço realizado não foi informado para o item da lista correspondente.',
  '52': 'Nenhum "valor tributável" do serviço realizado foi informado.',
  '53': 'Valor do ISSRF é superior ao valor tributável.',
  '54': 'Valor da dedução é superior ao valor tributável.',
  '55': 'Valor da soma (Dedução + ISSRF) é superior ao valor tributável.',
  '56': 'Soma dos valores tributáveis não pode ser zero ("0").',
  '57': 'Soma dos valores tributáveis não pode ser superior ao valor total da NFS-e.',
  '58': 'Nenhuma "situação tributária" foi informada.',
  '59': 'Código da situação tributária está ausente.',
  '60': 'Código da situação tributária não está preenchido corretamente.',
  '61': 'Código da situação tributária utilizado no item da lista é inválido.',
  '62': 'A situação tributária é TI (tributado integralmente), porém foi informado um valor para o ISSRF.',
  '63': 'A situação tributária é TI (tributado integralmente), porém foi informado um valor para dedução.',
  '64': 'O serviço foi declardo como TIRF, porém foi informado um valor para dedução.',
  '65': 'A situação tributária do serviço é TIRF, porém o valor do ISSRF não foi informado.',
  '66': 'A situação tributária do serviço é TIRF, porém o valor do ISSRF não foi informado corretamente.',
  '67': 'A situação tributária do serviço é TIRF, porém o valro do ISSRF foi declarado como zero (0,00).',
  '68': 'O serviço foi declarado como TIST, porém foi informado um valor para dedução.',
  '69': 'A situação tributária do serviço é TIST, porém o valor do ISSRF não foi informado.',
  '70': 'A situação tributária do serviço é TIST, porém o valor do ISSRF é inválido.',
  '71': 'A situação tributária do serviço é TIST, porém o valor do ISSRF foi declarado como zero (0,00).',
  '72': 'A situação tributária do serviço é TRBC (Tributada com redução da base de cálculo), porém foi informado um valor para o ISSRF.',
  '73': 'O valor da dedução para o serviço é inválido.',
  '74': 'O valor tributável para o serviço é inválido.',
  '75': 'O valor tributável do serviço não pode ser menor que o valor da dedução.',
  '76': 'O valor da dedução para o serviço só tem valiadde quando o código do serviço for 1705.',
  '77': 'A situação tributária do serviço é TRBCRF, porém o valor do ISSRF não foi informado.',
  '78': 'A situação tributária do serviço é TRBCRF, porém o valor do ISSRF é inválido.',
  '79': 'A situação tributária do serviço é TRBCRF, porém o valor do ISSRF foi declarado com zero (0,00).',
  '80': 'A situação tributária do serviço é TRBCST, porém o valor do ISSRF não foi informado.',
  '81': 'A situação tributária do serviço é TRBCST, porém o valor do ISSRF é inválido.',
  '82': 'A situação tributária do serviço é TRBCST, porém o valor do ISSRF foi declarado como zero (0,00).',
  '83': 'O serviço foi declarado como ISE (ISENTO), porém foi informado uma dedução para o item.',
  '84': 'O serviço foi declarado com ISE (ISENTO), porém foi informado um valor para o o ISSRF.',
  '85': 'O serviço foi declarado como IMU (IMUNE), porém foi informado uma dedução para o item.',
  '86': 'O serviço foi delcarado com IMU (IMUNE), porém foi informado um valor para o ISSRF.',
  '87': 'O serviço foi declarado como NTIFx (ISS regime Fixo), porém foi informado uma dedução para o item.',
  '88': 'O serviço foi declarado como NTIFx (ISS regime Fixo), porém foi informado um valor para o ISSRF.',
  '89': 'O serviço foi declarado como NTIEs (ISS regime Estimativa), porém foi informado um valor para a dedução.',
  '90': 'O serviço foi declarado como NTIEs (ISS Regime Estimativa), porém foi informado um valor para o ISSRF.',
  '91': 'O serviço foi declarado como NTICc (ISS Construção Civil), porém foi informado um valor para a dedução.',
  '92': 'O serviço foi declarado como NTICc (ISS Construção Civil), porém foi informado um valor para o ISSRF.',
  '93': 'O serviço foi declarado como NTAC (Ato Cooperado), porém foi informado um valor para dedução.',
  '94': 'O serviço foi declarado como NTAC (Ato Cooperado), porém foi informado um valor para o ISSRF.',
  '95': 'Situação tributária sem relacionamento definido.',
  '113': 'Soma dos valores tributáveis não pode ser menor que o valor total da NFS-e.',
  '114': 'Soma dos valores tributáveis não pode ser menor que o valor total da NFS-e (Configurado).',
  '115': 'Soma dos valores tributávies não pode ser menor que o valor total da NFS-e (Configurado).',
  '127': 'Código do local da prestação do serviço não foi encontrado na base de dados.',
  '128': 'Alíquota do item da lista de serviço enviada é diferente das alíquotas do SUPER SIMPLES.',
  '129': 'Alíquota enviada é diferente da alíquota do item da lista de serviço cadastrada.',
  '130': 'Nenhum item da lista de serviço foi enconrtado contendo o código enviado.',
  '141': 'Código de Autenticidade ausente no retorno do envio do arquivo.',
  '142': 'NFS-e não encontrada na tabela nfe.',
  '143':'Erro na tentativa de inserir o registro na tabela nfe.',
  '158': 'Alíquota do local da prestação do serviço não encontrada ou zerada.',
  '159': 'Alíquota enviada não pode ser inferior a 2% nem superior a 5%',
  '163': 'Serviço duplicado para a mesma cidade.',
  '166': 'Para utilizar Unidade de Serviço nos itens dos serviços é necessário informar os campos unidade_codigo, unidade_quantidade e unidade_valor_unitario',
  '167': 'A unidade do serviço correspondente ao código informado não foi encontrada.',
  '168': 'A quantidade da unidade do serviço não foi informada corretamente.',
  '169': 'O valor unitário da unidade do serviço não foi informado corretamente.',
  '170': 'O valor tributável do item do serviço é diferente da muktiplicação da quantidade da unidade com o valor da unidade.',
  '172': 'O serviço foi declarado como NTRIB, porém o cadastro econômico não possui permissão para declarar utilizando essa situação tributária.',
  '175': 'Item declarado como TIST, TIRF, TRBCRF ou TRBCST porém o valor do ISSRF não é compatível com o valor calculado (Valor tributável x Alíquota).',
  '177': 'O serviço foi declarado com NTICc (ISS Construção Civil), porém o cadastro econômico do prestador não está enquadrado para utilizar esta situaão tributária.',
  '178': 'O código da lista de serviço informado só pode ser utilizado com as situaçóes tributárias TRBC, TRBCRF, ou TRBCST quando houver relacionamento entre os mesmos previamente autorizado pela prefeitura.',
  '201': 'O item da lista de serviço não permite substituição tributária.',
  '243': 'O CEI informado não possui autorização para ser integrado com a NFS-e',

  //Gravação da NFS-e
  '101': 'A NFS-e não encontra-se declarada, impossibilitando o cancelamento.',
  '107': 'Erro na tentativa de inserir na tb nfe.nfeitem.',
  '112': 'Err na tentativa de gravar novo tomador de serviço.',
  '116': 'Erro na tentativa de gravar na tablea NFS-e.',
  '173': 'A base de dados atual já contém uma importação com o respectivo nome de arquivo.',
  '192': 'Erro na tentativa de realizar o update na tabela nf.wm_credito_iptu.',
  '193': ' O desconto não deve ser menor que zero.',
  '246': 'Contribuinte, a emissão de NFS-e está temporariamente bloqueada, para efetuar a liberação proceda com a protocolação das(s) competência(s) no Software Escrita Fiscal.',
  '248':'É necessário informar ao menos 5 caracteres na Tag Observação.',
  '251': 'A soma do valor líquido não pode ser negativa.',

  //Lançamento nas tabelas de Escrita Fiscal
  '108': 'NFS-e não foi inserida no software de Escrita Fiscal.',
  '109': 'Erro na tentativa de gravar na tabela de monitoração (monitora).',

  //Lançamento nas tabelas do móudlo de NFS-e
  '110': 'Erro na tentativa de inserir o HTML da NFS-e.',

  //Cancelamento da NFS-e
  '96': 'A situação (EMITIDA/CANCELADA) da NFS-e não foi informada.',
  '97': 'A situação da NFS-e não foi informada corretamente.',
  '98': 'O número da NFS-e não foi informado.',
  '99': 'O número da NFS-e foi informado incorretamente.',
  '117': 'A NFS-e já encontra-se cancelada.',
  '118': 'Não é necessário informar a data do cancelamento da NFS-e.',
  '119': 'Não é necessário informar as observações sobre o cancelamento da NFS-e.',
  '120': 'A NFS-e não pode ser cancelada pois foi gerada via sistema como FURMULÁRIO EM BRANCO.',
  '121': 'Para cancelar a NFS-e acesse o software de ESCRITA FISCAL ou procure a Prefeitura Municipal do seu município.',
  '122': 'A NFS-e não pode ser cancelada pois a competência relativa já foi protocolada.',
  '124': 'Erro na tentativa de inserir as informações no Escrita Fiscal.',
  '126': 'Erro na tentativa de cancelar a NFS-e.',
  '162': 'A data limite para o cancelamento da NFS-e foi ultrapassada pela data atual.',
  '194': 'Ultrapassou a quantidade de dias de emissão para o cancelamento da NFS-e.',
  '217': 'A NFS-e não pode ser cancelada pois ultrapassou o limite de horas configuradas para o cancelamento.',

  //Validações tributa no município do prestador
  '154': 'Verificar a situação TRIBUTA_MUNICIPIO_PRESTADOR.',
  '155': 'Situação indefinida para TRIBUTA_MUNICIPIO_PRESTADOR.',
  '156': 'Verificar alíquota para TRIBUTA_MUNICÍPIO_PRESTADOR.',
  '157': 'Situação indefinada para o resgate da alíquota TRIBUTA_MUNICIPIO_PRESTADOR',
  '160': 'A tag TRIBUTA_MUNICIPIO_PRESTADOR não foi preenchida ou foi preenchida incorretamente.',

  //Validações de pesquisa via web service
  '202': 'Código da autenticidade não informado no arquivo de pesquisa.',
  '203': 'Número da NFS-e não informado no arquivo de pesquisa.',
  '204': 'Série da NFS-e não informado no arquivo de pesquisa.',
  '205': 'A tag cadastro não foi informada no arquivo de pesquisa.',
  '206': 'Nenhuma NFS-e foi encontrada na base de dados utilizando os parâmetros para pesquisa informados.',
  '207': 'Usuário logado sem permissão para pesquisar essas NFS-e (Somente o prestador e o contador do respectivo cadastro, ou o tomador da NFS-e estão habilitados).',
  '208': 'A tag IDENTIFICADOR não foi preenchida corretamente.',
  '209': 'Já consta uma NFS-e para o referido prestador de serviço com o mesmo IDENTIFICADOR de arquivo.',
  '252': 'Arquivo temporário não encontrado no servidor.',

  //Validações uitlização de RPS - Recibo provisório de serviço
  '219': 'A série do RSP não foi informada.',
  '220': 'A série do RPS informada no arquivo é inválida.',
  '221': 'A série do RPS informada no arquivo é diferente da série do RPS utilizada pelo respectivo município.',
  '244': 'Não foi possível fazer a conversão. Quantidade de dias após a emissão do RPS é maior que a quantidade de dias limite para conversão.',
  '249': 'Número de RPS fora da sequência.',
  '250': 'Número de RPS está cancelado.',
  '280': 'Cidade informada não encontra-se cadastrada na base de dados do datacenter.',
  '281': 'Cadastro informado sem autorização para emissão de NFS-e com item zero (0).',

  //Validações assinatura digital (verificar obrigatoriedade com o município)
  '186': 'As assinaturas contidas no arquivo não fazem parte da lista dos responsáveis pelo prestador.',
  '187': 'Não foi encontrada nenhuma assinatura digital no arquivo enviado.',
  '188': 'Não foi possível conectar com o TOMCAT para validar a assinatura digital contida do arquivo enviado.',

  //Validações para utiização de forma de pagamento
  '268': 'A forma de pagamento informada não está prevista, informe uma das formas cadastradas no sistema (1 = À VISTA, 2 = À prazo, 3 = Na Apresentação, 4 = Cartão de Débito, 5 = Cartão de Crédito).',
  '269': 'A forma de pagamento informada exige pelo menos uma parcela com Número, Valor e Data de vencimento.',
  '270': 'O somatório das parcelas informadas não equivale ao valor total da NFS-e.',
  '271': 'Número da parcela informada inválido.',
  '272': 'O valor da parcela deve ser maior que zero.',
  '273': 'A data de vencimento da parcela é inválida.',
  '274': 'A quantidade de parcelas da forma de pagamento não pode ser maior que 24.',
  '275': 'Há parcelas duplicadas, verifique o número das parcelas.',
  '276': 'Erro ao inserir parcelas da forma de pagamento.',
  '277': 'O número da parcela não pode ser maior que 24.',
  '278': 'Parcela fora do sequencial, às parcelas da forma de pagamento devem começar pelo número 1 e manter um sequencial de no máximo 24 parcelas.'
}
